version: "3.7"
services:
  vaultd:
    image: williamofsino/vault:latest
    volumes:
      - ./testdata/:/testdata/
    ports:
      - "443:443"
      - "8080:8080"
      - "8081:8081"
    environment:
      - VAULTD_LOG_LEVEL=all
    networks:
      - vaultnet
    depends_on:
      - db
    command:
      [
        "-http-addr=:443",
        "-grpc-addr=:8080",
        "-debug-addr=:8081",
        "-tls-key=/testdata/server-key.pem",
        "-tls-cert=/testdata/server-cert.pem",
        "-pg-user=postgres",
        "-pg-password=postgres",
        "-pg-dbname=postgres",
        "-pg-host=db",
        "-pg-sslmode=disable",
        "-pg-port=5432",
      ]

  db:
    image: postgres:latest
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./pkg/store/.sql/schema.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
    networks:
      - vaultnet

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - vaultnet
    restart: always

networks:
  vaultnet:

volumes:
  db-data:
