# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run:
          name: Install Go 1.13
          command: |
            sudo rm -rf /usr/local/go
            wget -q https://dl.google.com/go/go1.13.linux-amd64.tar.gz
            sudo tar -C /usr/local -xzf go1.13.linux-amd64.tar.gz
            rm go1.13.linux-amd64.tar.gz
            which go
            go version
      - run:
          name: Run tests
          command: go test -v -race -tags tests github.com/williamlsh/vault/...
      - run:
          name: Run docker compose
          command: docker-compose -f docker-compose.yml up -d --force-recreate
    filters:
      branches:
        only:
          - master
          - feature/circleci
