name: Go
on: [push, pull_request]
jobs:
  test:
    name: Test all
    runs-on: [ubuntu-latest, macos-latest, windows-latest]
    strategy:
      matrix:
        go-version: [1.13]
    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v1.0.0
      - name: Test
        run: go test -v -race -tags tests ./...
