name: Vault
on: [push, pull_request]
jobs:
  test:
    name: Test all
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go-version: ["1.15"]
        os: [ubuntu-20.04]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go-version }}
      - name: Lint code base
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.29
        continue-on-error: true
  build:
    name: Build Docker image
    runs-on: ubuntu-20.04
    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000
    steps:
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
        with:
          driver-opts: network=host
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: localhost:5000/williamlsh/vault:latest
      - run: |
          docker buildx imagetools inspect localhost:5000/williamlsh/vault:latest
